version: "3.8"

services:
  ubuntu-server:
    build: .
    container_name: ubuntu-server
    ports:
      - 8080:8080
    environment:
      - TEST="ENV_TEST"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
